#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Enhance News Analysis Integration for Agent Input System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/balkhaev/mycode/trader"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check bun is installed
if ! command -v bun &> /dev/null; then
    echo -e "${RED}Error: bun is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}bun found${NC}"

# Check if in project directory
if [ ! -f "$PROJECT_ROOT/package.json" ]; then
    echo -e "${RED}Error: Not in project root directory${NC}"
    exit 1
fi
echo -e "${GREEN}Project root found${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Navigate to project root
cd "$PROJECT_ROOT"

# Start all services with bun dev (web:3001 + server:3000)
echo "Starting development servers..."
bun dev &
DEV_PID=$!

# Wait for services to start
wait_for_service 3000 "Server API"
wait_for_service 3001 "Web Frontend"

# ============================================
# VERIFY NEWS SCHEDULER
# ============================================

echo ""
echo "Verifying news system..."

# Check scheduler status
SCHEDULER_STATUS=$(curl -s http://localhost:3000/api/news/scheduler/status)
if echo "$SCHEDULER_STATUS" | grep -q '"isRunning":true'; then
    echo -e "${GREEN}News scheduler running${NC}"
else
    echo -e "${YELLOW}Warning: News scheduler may not be running${NC}"
    echo "Status: $SCHEDULER_STATUS"
fi

# Check realtime status
REALTIME_STATUS=$(curl -s http://localhost:3000/api/news/realtime/status)
if echo "$REALTIME_STATUS" | grep -q '"isRunning":true'; then
    echo -e "${GREEN}News realtime running${NC}"
else
    echo -e "${YELLOW}Warning: News realtime may not be running${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Server API:   http://localhost:3000"
echo "  Web Frontend: http://localhost:3001"
echo ""
echo "News System:"
echo "  Scheduler Status: http://localhost:3000/api/news/scheduler/status"
echo "  Realtime Status:  http://localhost:3000/api/news/realtime/status"
echo ""
echo "Useful Commands:"
echo "  bun check        - Run linter"
echo "  bun check-types  - TypeScript check"
echo "  bun db:studio    - Open Drizzle Studio"
echo ""
echo "Process PID: $DEV_PID"
echo ""
echo "To stop: kill $DEV_PID"
