import type { StrategyConfig } from "@trader/db";

export function generateConsensusLeanCode(config: StrategyConfig): string {
  const serialized = JSON.stringify(config, null, 2);
  return `# region imports
from AlgorithmImports import *
# endregion

# Generated by Trader from Consensus WIF + DOT Risk Accelerator V1.
# The production signal scanner lives in apps/server and supplies precomputed
# WIF OI/volume features and already-known DOT funding observations.
STRATEGY_CONFIG = ${serialized}


class ConsensusWifDotRiskAccelerator(QCAlgorithm):
    def initialize(self):
        self.set_start_date(2024, 1, 1)
        self.set_cash(10000)
        self.set_brokerage_model(BrokerageName.BINANCE, AccountType.MARGIN)
        self.wif = self.add_crypto("WIFUSDT", Resolution.MINUTE, Market.BINANCE).symbol
        self.dot = self.add_crypto("DOTUSDT", Resolution.MINUTE, Market.BINANCE).symbol
        self.initial_equity = self.portfolio.total_portfolio_value
        self.high_water = self.initial_equity
        self.risk_mode = "base"
        self.positions_meta = {}
        self.debug("Use the canonical project in apps/lean/Consensus WIF DOT Risk Accelerator for feature-data wiring.")

    def on_data(self, data: Slice):
        self._update_risk_mode()
        self._manage_time_exits()

    def _update_risk_mode(self):
        equity = float(self.portfolio.total_portfolio_value)
        self.high_water = max(self.high_water, equity)
        drawdown = 1 - equity / self.high_water if self.high_water else 1
        profit = equity / self.initial_equity - 1 if self.initial_equity else 0
        if drawdown >= ${config.risk.hardStopDrawdownPercent / 100}:
            self.risk_mode = "stopped"
            return
        if self.risk_mode == "boost" and drawdown >= ${config.risk.deRiskDrawdownPercent / 100}:
            self.risk_mode = "base"
        elif self.risk_mode == "base" and profit >= ${config.risk.boostTriggerProfitPercent / 100} and abs(equity - self.high_water) < 1e-8:
            self.risk_mode = "boost"

    def target_risk(self, module):
        if self.risk_mode == "stopped":
            return 0
        if module == "wif":
            return ${config.risk.baseWifRiskPercent / 100} if self.risk_mode == "base" else ${config.risk.boostWifRiskPercent / 100}
        return ${config.risk.baseDotRiskPercent / 100} if self.risk_mode == "base" else ${config.risk.boostDotRiskPercent / 100}

    def enter_from_precomputed_signal(self, symbol, module, entry_price, atr, stop_atr, target_r, hold_minutes):
        if self.risk_mode == "stopped" or self.portfolio[symbol].invested:
            return
        stop_distance = atr * stop_atr
        if entry_price <= 0 or stop_distance <= 0:
            return
        equity = float(self.portfolio.total_portfolio_value)
        risk = self.target_risk(module)
        notional = min(equity * risk / (stop_distance / entry_price), equity * ${config.execution.maxGrossLeverage})
        quantity = notional / entry_price
        self.market_order(symbol, quantity)
        self.positions_meta[symbol] = {
            "stop": entry_price - stop_distance,
            "target": entry_price + stop_distance * target_r,
            "exit_at": self.time + timedelta(minutes=hold_minutes),
        }

    def _manage_time_exits(self):
        for symbol, meta in list(self.positions_meta.items()):
            if not self.portfolio[symbol].invested:
                del self.positions_meta[symbol]
                continue
            price = float(self.securities[symbol].price)
            if price <= meta["stop"] or price >= meta["target"] or self.time >= meta["exit_at"]:
                self.liquidate(symbol)
                del self.positions_meta[symbol]
`;
}
